version: "3"
services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/postgres_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_pwd
      - WAIT_FOR=db:5432
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pwd
      - POSTGRES_DB=postgres_db
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    restart: always
    build:
      context: .
    command: ["gunicorn --bind 0.0.0.0:80 rebus_hackaton.wsgi:application"]
    depends_on:
      - db
      - camunda
    ports:
      - "8000:80"
    volumes:
      - ./:/app/

volumes:
  pgdata: {}
