version: "3"
services:
  api:
    restart: always
    build:
      context: .
    command: ["gunicorn --bind 0.0.0.0:80 rebus_hackaton.wsgi:application"]
    ports:
      - "8000:80"
    volumes:
      - ./:/app/
